services:
  mysql:
    image: mysql:8.4
    container_name: tera_atacado_mysql
    restart: unless-stopped
    command: --log-bin-trust-function-creators=1
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./Back_end
      dockerfile: Dockerfile
    container_name: "Backend_tera_atacado"
    restart: unless-stopped
    
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    ports:
      - "8080:80"

    volumes:
      - "./:/var/www/html"
  
volumes:
  mysql_data:
